# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tesxt',
            field=models.TextField(default=''),
        ),
    ]
