# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-03 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_tesxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tesxt',
            new_name='text',
        ),
    ]
